version: '3'

services:
  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
  redis:
    image: "redis:alpine"
  web:
    build:
      context: .
      dockerfile: local.dockerfile
    volumes:
      - .:/code
    ports:
      - "8057:8000"
    depends_on:
      - db
      - redis
    command: /bin/sh /code/local.sh
  celery-workers:
    build:
      context: .
      dockerfile: local.dockerfile
    command: /bin/bash -c "cd app; DEBUG=False celery -E -A core worker -l info"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: local.dockerfile
    command: /bin/bash -c "cd app; DEBUG=False celery -A core beat -l info --pidfile /tmp/celerybeat.pid -s /tmp/celerybeat-schedule"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-flower:
    build:
      context: .
      dockerfile: local.dockerfile
    ports:
      - "5555:5555"
    command: /bin/bash -c "cd app; DEBUG=False celery flower -A core"
    volumes:
      - .:/code
    depends_on:
      - redis
      - celery-workers
      - celery-beat
volumes:
  postgres_data:


