version: '3'

services:
  db:
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
  redis:
    image: "redis:alpine"
  web:
    build:
      context: .
      dockerfile: local.dockerfile
    volumes:
      - .:/code
    environment:
      - LOCAL_ENV=local.env
    ports:
      - "8057:8000"
    depends_on:
      - db
      - redis
    command: /bin/sh /code/local.sh
  web_nginx:
    build:
      context: .
      dockerfile: local.dockerfile
    #    volumes:
    #  - .:/code
    ports:
      - "8058:8000"
    command: /usr/sbin/nginx -c /code/local-nginx.conf -g "daemon off;"
    # command: /bin/bash -c "/usr/sbin/nginx -c /code/nginx.conf -g 'daemon off;' >/dev/null 2>&1"
  celery-workers:
    build:
      context: .
      dockerfile: local.dockerfile
    environment:
      - LOCAL_ENV=local.env
    command: /bin/bash -c "cd app; celery -E -A app worker -l info"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: local.dockerfile
    environment:
      - LOCAL_ENV=local.env
    command: /bin/bash -c "cd app; celery -A app beat -l info --pidfile /tmp/celerybeat.pid -s /tmp/celerybeat-schedule"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:


