version: '3'

services:
  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  redis:
    image: redis:alpine

  web:
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "8057:8000"
    depends_on:
      - db
      - redis
      - web_nginx
    command: /bin/sh /code/run.sh

  web_nginx:
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "8058:8000"
    command: /code/prod-nginx.sh

  celery_workers:
    build:
      context: .
      dockerfile: prod.dockerfile
    command: /bin/bash -c "cd app; DEBUG=False exec celery -E -A core worker -l info"
    depends_on:
      - db
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: prod.dockerfile
    command: /bin/bash -c "cd app; DEBUG=False exec celery -A core beat -l info --pidfile /tmp/celerybeat.pid -s /tmp/celerybeat-schedule"
    depends_on:
      - db
      - redis

  celery_flower:
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "5555:5555"
    command: /bin/bash -c "cd app; DEBUG=False celery flower -A core"
    depends_on:
      - redis
      - celery_workers
      - celery_beat

volumes:
  postgres_data:


