version: '3'

services:
  db:
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
  redis:
    image: "redis:alpine"
  web:
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "8057:8000"
    depends_on:
      - db
      - redis
      - web_nginx
    command: /bin/sh /code/run.sh
  web_nginx:
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "8058:8000"
    command: /code/prod-nginx.sh
    # command: /bin/bash -c "/usr/sbin/nginx -c /code/nginx.conf -g 'daemon off;' >/dev/null 2>&1"
  celery-workers:
    build:
      context: .
      dockerfile: prod.dockerfile
    command: /bin/bash -c "cd app; exec celery -E -A app worker -l info"
    depends_on:
      - db
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: prod.dockerfile
    command: /bin/bash -c "cd app; exec celery -A app beat -l info --pidfile /tmp/celerybeat.pid -s /tmp/celerybeat-schedule"
    depends_on:
      - db
      - redis
volumes:
  postgres_data:


